### ISSUE TITLE
Segfault upon running

### ISSUE THREAD

**Issue by orinatic** [diepbp/FAT#7]
Hello!

I installed Trau according to the instructions (I think). When I try to run it, I get to the 'Running z3' line, and then it segfaults. Running it in GDB gives the following trace. I have confirmed that the libz3.so in /usr/local/lib is the custom one, and I've added the custom python2.7/dist-packages into /usr/local/lib/python2.7/dist-packages

Please let me know if you have any advice on getting this running properly!

```
(gdb) r
Starting program: /home/ebdavis/Downloads/Trau/build/Trau ../examples/concat-006
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Running Over Approximation
..
Running Under Approximation
>> Generated SMT

>> Running Z3


Program received signal SIGSEGV, Segmentation fault.
Z3_run (cmd="z3 -smt2 /tmp/fat_str_convert/_trau_output_concat-006", _equalMap=std::map with 2 elements = {...}, finalCall=finalCall@entry=true) at ../src/UnderApprox.cpp:4862
4862                                                                                    if (tokens[i + 5][0] >= '0' && tokens[i + 5][0] <= '9')
(gdb) bt
#0  Z3_run (cmd="z3 -smt2 /tmp/fat_str_convert/_trau_output_concat-006", _equalMap=std::map with 2 elements = {...}, finalCall=finalCall@entry=true) at ../src/UnderApprox.cpp:4862
#1  0x0000000000591d92 in underapproxController (_equalMap=std::map with 3 elements = {...}, _fullEqualMap=std::map with 2 elements = {...}, rewriterStrMap=std::map with 1 elements = {...},
								    _carryOnConstraints=std::set with 0 elements, _currentLength=std::map with 0 elements, fileDir="/tmp/fat_str_convert/concat-006", _connectedVars=std::set with 0 elements,
								    _excludeSet=std::set with 0 elements, _lazy=@0x7fffffffd17f: true, wellForm=false) at ../src/UnderApprox.cpp:5760
#2  0x0000000000536a72 in Th_final_check (t=0x9f9528) at ../src/StringTheory.cpp:6423
#3  0x00007ffff714a5d1 in smt::user_theory::final_check_eh() () from /usr/local/lib/libz3.so
#4  0x00007ffff712b051 in smt::context::final_check() () from /usr/local/lib/libz3.so
#5  0x00007ffff712bad7 in smt::context::bounded_search() () from /usr/local/lib/libz3.so
#6  0x00007ffff712bd48 in smt::context::search() () from /usr/local/lib/libz3.so
#7  0x00007ffff712cb9f in smt::context::check(unsigned int, expr* const*, bool) () from /usr/local/lib/libz3.so
#8  0x00007ffff6c23a07 in api::context::check(ref<model>&) () from /usr/local/lib/libz3.so
#9  0x00007ffff6c0ba02 in Z3_check_and_get_model () from /usr/local/lib/libz3.so
#10 0x000000000052ace9 in check (t=t@entry=0x9f9528) at ../src/StringTheory.cpp:10140
#11 0x000000000052ba16 in overApproxController () at ../src/StringTheory.cpp:10250
#12 0x000000000042a062 in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:192
(gdb)
```

**Comment by diepbp** [comment]
Hi,

Which version of Z3 are you using?

**Comment by orinatic** [comment]
I am not sure what my problem was, but using your new shiny install script fixed it. Thank you!
